name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  publish:
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      id-token: write # required for npm trusted publishing (OIDC)
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build

      - name: Publish
        run: npm publish
